### ISSUE TITLE
Hashing: Why not using hash/fnv?

### ISSUE THREAD

**Issue by aaronwinter** [orcaman/concurrent-map#56]
Context: concurrent-map uses `FNV-1` (see: http://www.isthe.com/chongo/tech/comp/fnv/) to consistently map keys to one of its internal shards.

Surprisingly, it does not make use of [hash/fnv](https://golang.org/pkg/hash/fnv/), but instead relies on a custom implementation (see: https://github.com/orcaman/concurrent-map/blob/master/concurrent_map.go#L285).

I was about to make a PR to correct this, but I noticed that in the tests we actually check the behavior of the custom implementation against [hash/fnv](https://golang.org/pkg/hash/fnv/) (see: https://github.com/orcaman/concurrent-map/blob/master/concurrent_map_test.go#L389).

What is the reason for that? I see that the native implementation is stateful but this can be work-around easily:

```
// Returns shard under given key
func (m ConcurrentMap) GetShard(key string) *ConcurrentMapShared {
	return m[uint(fnv32(key))%uint(SHARD_COUNT)]
}
```

would become:

```
// Returns shard under given key
func (m ConcurrentMap) GetShard(key string) *ConcurrentMapShared {
        hash := fnv.New32()
        hash.Write([]byte(key))
        hashKey := hash.Sum32()
        return m[hashKey%uint32(SHARD_COUNT)]
}
```

which is slightly more verbose, but makes us rely on a maintained implementation of FNV-1. Is there a reason I am not seeing for this?

**Comment by aaronwinter** [comment]
ping @orcaman

**Comment by orcaman** [comment]
Hi @aaronwinter 

Thanks for raising this, and sorry for the belated response. 

There isn't a good reason for us not using the native fnv implementation. We initially thought that our implementation is faster, but it turned out our benchmark was wrong. 

I think it's a good idea to migrate to the native implementation as you suggest, however we need to benchmark it (for instance, it looks like you're allocating a new hasher for every function call - will this slow us down?). 

Would be cool if you could perform this change along with some simple benchmarking code and send a PR. If performance is comparable (no reason why it shouldn't be) I'll be happy to merge.

Cheers,
Or

**Comment by aaronwinter** [comment]
Sounds good, thanks for the reply
