### ISSUE TITLE
Using with goroutines

### ISSUE THREAD

**Issue by sunnylbk** [orcaman/concurrent-map#87]
Hello
Thank you for this library.

I am trying to use a concurrent map to write from go routines, here is a test

```
func TestCMap(t *testing.T) {
	var wg sync.WaitGroup

	cm := cmap.New()

	go func() {
		defer wg.Done()
		wg.Add(1)
		for i := 0; i < 10; i++ {
			cm.Set(strconv.Itoa(i), i)
		}
	}()

	wg.Wait()
	fmt.Println(cm.Items())
	fmt.Println(cm.Items())
}
```

Output of this:

```
=== RUN   TestCMap
map[0:0 2:2 3:3 4:4]
map[0:0 1:1 2:2 3:3 4:4 5:5 6:6 7:7 8:8 9:9]
--- PASS: TestCMap (0.00s)
```

The map seems to be eventually consistent. Am I using this the right way?

Thanks

**Comment by orcaman** [comment]
Hi @sunnylbk , thanks for reporting this.
The thing is: the map is immediately consistent, however, the `Items()` function is eventually consistent. This is because, when you, for example, try to `Get` an item from the map - it is read directly from the appropriate shard. On the contrary, when you call `Items()` - a snapshot of the map is being created (this is the part that causes the Items function to be eventually consistent indeed).

**Comment by sunnylbk** [comment]
I see, cool, thanks!
